"""Campaign close-out / ROI report (Intelligence Phase 5).

Turns a campaign's performance data into a short narrative wrap-up: adoption, what landed, where it
was missed, the standout reps, and a verdict + recommendation for next time. Generated by Claude from
the analytics (numbers preserved). Most useful once a campaign has ended."""
from __future__ import annotations

import json
import logging
from datetime import datetime

from ...config import settings
from .analytics import campaign_performance
from .models import Campaign
from .services import status_of

log = logging.getLogger("calliq.campaign_closeout")


def closeout_report(db, c: Campaign) -> dict:
    perf = campaign_performance(db, c)
    base = {"name": c.name, "type": c.type, "status": status_of(c),
            "startDate": c.start_date.isoformat(), "endDate": c.end_date.isoformat(),
            "generatedAt": datetime.utcnow().isoformat()}
    if (perf.get("totals") or {}).get("calls", 0) == 0:
        return {**base, "report": "No calls were tracked while this campaign was live, so there's "
                "nothing to report on yet.", "source": "facts"}
    if not settings.anthropic_api_key:
        t = perf["totals"]
        return {**base, "source": "facts",
                "report": (f"'{c.name}' was addressed on {t['addressed']} of {t['calls']} calls "
                           f"({perf.get('adoptionRate')}% adoption). Reactions: {perf['reactions']}. "
                           f"Quality when addressed {perf['quality'].get('addressed')} vs missed "
                           f"{perf['quality'].get('missed')}.")}
    from ...pipeline.analyzer import _claude
    system = (
        "You are a UK B2B telecoms sales manager writing a short close-out report for a sales campaign "
        "(promotion or incentive). Use ONLY the supplied analytics; quote the figures; never invent "
        "numbers. Cover: adoption, customer reaction, quality impact, standout reps, and a clear verdict "
        "+ one recommendation for next time. 150–250 words, UK English, plain prose with light headings."
    )
    user = (f"Campaign: {c.name} ({c.type}), {base['startDate']}→{base['endDate']}.\n\n"
            f"Analytics:\n{json.dumps(perf, indent=1, default=str)}")
    try:
        report = _claude(system, user, settings.claude_report_model, max_tokens=1200)
        return {**base, "report": report, "source": "ai"}
    except Exception as e:
        log.warning("campaign closeout LLM failed: %s", e)
        return {**base, "source": "facts",
                "report": f"Adoption {perf.get('adoptionRate')}% across {perf['totals']['calls']} calls."}
