"""Auto 1-to-1 brief (Intelligence Phase 3).

Compiles everything RepIQ knows about a rep — their open insights, metrics vs the team, benchmark
rank, and the recurring coaching points from recent calls — into a manager's 1-to-1 prep: what's
going well, the focus areas (with evidence), and ready-to-use talking points. Generated by Claude
from the structured facts (numbers preserved), so it reads like a thoughtful manager wrote it.
Surfaced in the HR Performance/Reviews tab.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime

from ...config import settings
from ...models import CallAnalysis, Call, Insight, User
from .common import rep_averages, team_averages

log = logging.getLogger("calliq.one2one")


def _facts(db, user: User, days: int) -> dict:
    uid = user.id
    insights = (db.query(Insight)
                .filter(Insight.scope == "rep", Insight.subject_id == uid,
                        Insight.status.in_(("new", "acknowledged", "actioned"))).all())
    ins = [{"category": i.category, "severity": i.severity, "title": i.title,
            "body": i.body, "recommendation": i.recommendation} for i in insights]

    ravg = rep_averages(db, uid, days=days)
    team = team_averages(db, days=days)
    bench = {}
    try:
        from .benchmarks import rep_vs_team
        b = rep_vs_team(db, uid, weeks=8)
        bench = {"qualityRank": (b.get("qualityRank") or {}).get("label"),
                 "myQuality": b.get("myQuality"), "teamQuality": b.get("teamQuality"),
                 "myOrders": b.get("myOrders"), "teamOrdersAvg": b.get("teamOrdersAvg")}
    except Exception:
        pass

    # recurring coaching points from recent calls
    things = [t for (t,) in (db.query(CallAnalysis.one_thing)
              .join(Call, Call.id == CallAnalysis.call_id)
              .filter(Call.host_id == uid, Call.status == "completed")
              .order_by(Call.started_at.desc()).limit(12).all()) if t]
    # Weekly-forecast standing — reliability is a core performance dimension in every 1-to-1.
    forecast = None
    try:
        from ...modules.forecast import services as _fc
        if _fc.is_rep(db, user):
            s = _fc.rep_signal(db, user)
            forecast = {"summary": s["summary"], "reliabilityScore": s["reliabilityScore"],
                        "band": s["reliabilityBand"], "weeksTracked": s["weeks"], "hits": s["hitCount"],
                        "thisWeekPct": s["thisWeekPct"], "behindPace": s["behindPace"],
                        "components": s["components"],
                        "flags": [k for k in ("chronicMiss", "strong", "sandbagger", "notSubmitted") if s.get(k)]}
    except Exception:
        pass

    # The rep's own reflection on their latest review — start the 1-to-1 from what they already said.
    reflection = None
    try:
        from ...modules.reflections import services as _rf
        s = _rf.reflection_signal(db, user)
        if s.get("status") not in (None, "none"):
            reflection = {"signalSummary": s.get("summary"), "summary": s.get("summaryText"),
                          "openCommitments": s.get("openCommitments"),
                          "blockersNeedingHelp": s.get("blockersNeedingHelp"),
                          "engagement": s.get("engagement"), "selfAwareness": s.get("selfAwareness"),
                          "flags": [k for k, v in (s.get("flags") or {}).items() if v]}
    except Exception:
        pass

    return {"name": user.short_name or user.name, "insights": ins, "reflection": reflection,
            "metrics": {"calls": ravg.get("calls"), "quality": ravg.get("quality"),
                        "questions": ravg.get("questions"), "talk_ratio": ravg.get("talk_ratio"),
                        "interruptions": ravg.get("interruptions"), "closeRate": ravg.get("closeRate"),
                        "orders": ravg.get("orders")},
            "team": {"quality": team.get("quality"), "questions": team.get("questions"),
                     "closeRate": team.get("closeRate")},
            "forecast": forecast,
            "benchmark": bench, "recentCoachingPoints": things, "days": days}


_FALLBACK_KEYS = ("headline", "goingWell", "focusAreas", "talkingPoints")


def brief(db, user_id: int, days: int = 30) -> dict:
    user = db.get(User, user_id)
    if not user:
        raise ValueError("User not found")
    facts = _facts(db, user, days)

    if not settings.anthropic_api_key:
        # deterministic fallback from the structured facts
        return {
            "name": facts["name"], "generatedAt": datetime.utcnow().isoformat(),
            "headline": f"{facts['name']}: {facts['metrics'].get('calls') or 0} calls, quality {facts['metrics'].get('quality')}.",
            "goingWell": [i["title"] for i in facts["insights"] if i["severity"] == "positive"][:3],
            "focusAreas": [{"title": i["title"], "evidence": i["body"], "action": i["recommendation"]}
                           for i in facts["insights"] if i["severity"] != "positive"][:4],
            "talkingPoints": [i["recommendation"] for i in facts["insights"]][:4],
            "metrics": facts["metrics"], "benchmark": facts["benchmark"], "source": "facts",
        }

    from ...pipeline.analyzer import _claude, _extract_json
    system = (
        "You are an experienced sales manager at BT Local Business Oxford & Bucks (UK B2B telecoms) "
        "preparing for a 1-to-1 with one of your reps. Using ONLY the supplied facts, write a warm, "
        "specific, evidence-based prep brief. Lead with genuine positives, be constructive on gaps, and "
        "give the manager concrete talking points and questions to ask. Where the facts include a "
        "'forecast' block, treat weekly-forecast reliability as a key performance dimension — praise "
        "consistency, address chronic misses or sandbagging, and reference this week's pacing. Where "
        "the facts include a 'reflection' block, lead with the rep's OWN words and the commitments they "
        "made — open from what they already said, follow up on their stated blockers, and gently address "
        "any gap between their self-view and the data. Keep "
        "every number EXACTLY as given; never invent figures. UK English. Return STRICT JSON only."
    )
    user_msg = (
        "Facts:\n" + json.dumps(facts, indent=1, default=str) +
        "\n\nReturn JSON: {\"headline\":\"one line summary of where they are\","
        "\"goingWell\":[\"2-3 specific strengths with evidence\"],"
        "\"focusAreas\":[{\"title\":\"…\",\"evidence\":\"the data behind it\",\"action\":\"what to coach\"}],"
        "\"talkingPoints\":[\"3-5 questions/prompts for the manager to use in the 1-to-1\"]}"
    )
    try:
        data = _extract_json(_claude(system, user_msg, settings.claude_call_model, max_tokens=1600))
    except Exception as e:
        log.warning("1-to-1 brief LLM failed for %s: %s", user_id, e)
        data = {}
    out = {k: data.get(k) for k in _FALLBACK_KEYS}
    out["name"] = facts["name"]
    out["metrics"] = facts["metrics"]
    out["benchmark"] = facts["benchmark"]
    out["generatedAt"] = datetime.utcnow().isoformat()
    out["source"] = "ai" if data else "facts"
    if not data:                      # LLM hiccup → fall back to facts
        out["headline"] = f"{facts['name']}: {facts['metrics'].get('calls') or 0} calls this period."
        out["goingWell"] = [i["title"] for i in facts["insights"] if i["severity"] == "positive"][:3]
        out["focusAreas"] = [{"title": i["title"], "evidence": i["body"], "action": i["recommendation"]}
                             for i in facts["insights"] if i["severity"] != "positive"][:4]
        out["talkingPoints"] = [i["recommendation"] for i in facts["insights"]][:4]
    return out
